server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    allow-circular-references: true

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - StripPrefix=1  # use 1 if your controller is already at "/api/auth"

        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/documents/**
      csrf:
        enabled: false

  security:
    reactive:
      csrf:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: HBXtaDT+6oVTryG1wu1NoJvR3lXr4M77tn5QHzXvalbiZ8hwxRntEWPode0ZiL7F1ndZi+9FeAA4xJO2KYU3lg==

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
