spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb+srv://user1:IOCEZCXnmlB9YrvZ@cluster0.itsriak.mongodb.net/userdb?retryWrites=true&w=majority&appName=Cluster0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8082

jwt:
  secret: HBXtaDT+6oVTryG1wu1NoJvR3lXr4M77tn5QHzXvalbiZ8hwxRntEWPode0ZiL7F1ndZi+9FeAA4xJO2KYU3lg==

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.deepak.dms.user-service: DEBUG   # replace with your base package for user-service code (e.g., com.example.userservice)
    io.jsonwebtoken: DEBUG   # JWT library logs (if you use jjwt)
