spring:
  application:
    name: document-service

  data:
    mongodb:
      uri: mongodb+srv://user1:IOCEZCXnmlB9YrvZ@cluster0.itsriak.mongodb.net/documentdb?retryWrites=true&w=majority&appName=Cluster0
      database: documentdb

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: HBXtaDT+6oVTryG1wu1NoJvR3lXr4M77tn5QHzXvalbiZ8hwxRntEWPode0ZiL7F1ndZi+9FeAA4xJO2KYU3lg==

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.deepak.dms.document_service: DEBUG  # ✅ Replace with the correct base package if needed
    io.jsonwebtoken: DEBUG  # Optional: if JWT verification happens in this service

