spring:
  application:
    name: document-service

  data:
    mongodb:
      uri: mongodb+srv://user1:IOCEZCXnmlB9YrvZ@cluster0.itsriak.mongodb.net/dms-document-db?retryWrites=true&w=majority&appName=Cluster0

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

